# Configuration file for the web search app
DEBUG: true
DF_SEARCH_HISTORY_FILENAME: "df_search_history.parquet"
DF_SEARCH_HISTORY_UPDATES_FILENAME: "df_search_history_updates.xlsx"
DF_SEARCH_TASKS_FILENAME: "df_search_tasks.xlsx"
DF_CONSUMPTION_FILENAME: "df_consumption.parquet"
API_PRICING_FILENAME: "app_data/api_pricing.xlsx"
SUBSCRIPTIONS_FILENAME: "app_data/subscriptions.xlsx"
EMAIL_TEMPLATE_FILENAME: "template_email.md"
EMAIL_TEMPLATE_SPREADSHEET_FILENAME: "template_email_spreadsheet.md"
BUSINESS_DESCRIPTION_FILENAME: "prompt_businessdescription.md"

# The following must be environment variables:
# ENVIRONMENT:
# AZURE_STORAGE_CONNECTION_STRING:
# AZURE_CONTAINER_NAME:

