cookie:
  expiry_days: 30
  key: random_signature_key_12345
  name: mindsearch_auth_cookie
credentials:
  usernames:
    admin:
      client: ['Client1']
      email: admin@example.com
      name: Administrator
      password: 
      role: admin
    user1:
      client: Client1
      email: user1@client1.com
      name: User One
      password: 
      role: user
